repos:
  - repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.3.0
    hooks:
      - id: pre-commit-update
        args: [--dry-run]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
        args: [--lock]
      - id: poetry-export
        args: [--format, requirements.txt, --without-hashes, --output, requirements.txt]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-python-dateutil"]
