repos:
  - repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.1.5
    hooks:
      - id: pre-commit-update
        args: [--dry-run]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.3
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, --production, --without-hashes]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-python-dateutil"]
