[project]
name = "sunspot"
version = "0.1.0"
description = "sunspot code written in python"
requires-python = ">=3.10"
dependencies = [
    "polars",
    "python-dateutil",
    "suntime",
    "numpy",
    "matplotlib",
    "scipy",
    "scikit-learn",
]

[project.optional-dependencies]
dev = [
    "taskipy",
    "pre-commit",
    "black",
    "isort",
    "ruff",
    "mypy",
    "types-python-dateutil",
    "pytest",
    "pytest-cov",
    "tox",
]

[tool.black]
target-version = ["py310"]
line-length = 79

[tool.isort]
profile = "black"

[tool.ruff]
src = ["src"]
target-version = "py310"
output-format = "grouped"
select = ["ALL"]
ignore = ["D", "FA", "T20", "INP", "PD"]
unfixable = ["I", "ERA"]

[tool.ruff.per-file-ignores]
"test/*.py" = ["S101", "FBT001", "PLR0913", "PLR2004"]

[tool.mypy]
python_version = "3.10"
show_error_context = true
show_column_numbers = true
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "src"
addopts = ["--import-mode=importlib"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py310,py311,py312,lint
skipsdist = true
skip_missing_interpreters = true

[testenv]
deps = -rdev-requirements.txt
commands = pytest test

[testenv:lint]
skip_install = true
commands =
    black --check src test
    ruff check src test
    mypy src test
"""

[tool.taskipy.tasks]
lock = "pip-compile -U pyproject.toml -o requirements.txt"
sync = "pip-sync requirements.txt"
update = "task lock && task sync"
lock-dev = "pip-compile -U --all-extras pyproject.toml -o dev-requirements.txt"
sync-dev = "pip-sync dev-requirements.txt"
update-dev = "task lock-dev && task sync-dev"
format = "black src test && isort src test"
lint = "black --check src test && ruff check src test && mypy src test"
test = "pytest test"
test-doc = "pytest --doctest-modules --doctest-continue-on-failure src"
test-cov = "pytest --cov src --cov-branch --cov-report=term-missing src test"
test-all = "tox"
