[project]
name = "sunspot"
version = "0.1.0"
description = "sunspot code written in python"
requires-python = ">=3.10"
dependencies = ["polars", "python-dateutil", "suntime", "numpy", "matplotlib"]

[project.optional-dependencies]
dev = [
    "taskipy",
    "pre-commit",
    "black",
    "isort",
    "ruff",
    "mypy",
    "types-python-dateutil",
    "pytest",
    "pytest-cov",
]

[tool.black]
target-version = ["py310"]
line-length = 79

[tool.isort]
profile = "black"

[tool.ruff]
src = ["src"]
target-version = "py310"
output-format = "grouped"
select = ["ALL"]
ignore = ["D", "FA", "T20", "INP", "PD"]
unfixable = ["I", "ERA"]

[tool.ruff.per-file-ignores]
"test/*.py" = ["S101", "FBT001", "PLR0913", "PLR2004"]

[tool.mypy]
python_version = "3.10"
show_error_context = true
show_column_numbers = true
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["test"]

[tool.taskipy.tasks]
lock = "pip-compile -U pyproject.toml -o requirements.txt"
sync = "pip-sync requirements.txt"
update = "task lock && task sync"
lock-dev = "pip-compile -U --all-extras pyproject.toml -o dev-requirements.txt"
sync-dev = "pip-sync dev-requirements.txt"
update-dev = "task lock-dev && task sync-dev"

black = "black src test"
black-check = "black --check src test"
isort = "isort src test"
ruff = "ruff src test"
ruff-fix = "ruff --fix src test"
mypy = "mypy src test"
pytest = "pytest test"
pytest-v = "pytest -v test"
pytest-cov = "pytest --cov src --cov-branch --cov-report=term-missing test"
format = "task black && task isort"
lint = "task black-check && task ruff && task mypy"
test = "task pytest"
test-cov = "task pytest-cov"
fix = "task ruff-fix"
